# Reconnaissance des Digits basée sur les enregistrements Audios 

### Importer les bibliothéques necessaires 

In [1]:
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sb
sb.set_style("whitegrid", {'axes.grid' : False})
sb.set(font_scale = 2)
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier 

In [2]:
from Tools.tools import collection

### Collection 

collection()

#### 1. Importer votre DataSet

In [3]:
mydata = pd.read_csv('./DataSet/'+os.listdir('./DataSet/')[0])

##### Print

In [4]:
mydata.head(10)

Fe1        Fe2        Fe3       Fe4       Fe5        Fe6       Fe7  \
0  14.009980 -10.883263   4.365307  4.986854  2.435013 -12.367657  0.054216   
1  12.618823 -18.567271  -0.825264 -2.935280 -1.252682 -10.560307  3.010610   
2  12.210632 -26.004803  -5.622614 -6.454565  0.081624  -6.172828  4.900269   
3  13.355268 -14.450084   0.671483  0.231994  1.089737 -11.538107  2.880812   
4  12.582414 -20.048431   0.236620 -7.352642 -2.680846  -5.635102  4.440549   
5  11.374867  -8.261425  -6.674204 -3.537265 -2.049147 -15.256732  2.372672   
6  15.130975 -10.398570  -7.273264  6.777935 -0.092872 -22.594124  3.398076   
7  10.447524 -29.542980 -12.875895 -4.500975  0.207055 -10.310458  5.883562   
8  14.790805  -8.729446   0.229353 -1.228610  0.464105 -11.152055  5.661992   
9  14.021282 -12.026842  -2.831477  1.722735  0.554000 -11.666233  6.743605   

        Fe8        Fe9      Fe10      Fe11      Fe12  Target  
0 -6.505667  -6.805871  2.364852 -4.845748 -4.725184     0.0  
1  0.327419   0.905538  6.674397 -0.364233 -4.261779     1.0  
2 -0.985544  -3.634996  0.872817 -2.394720 -4.316653     2.0  
3 -1.121280  -4.081854  2.172804 -3.672594 -6.359476     3.0  
4 -3.257457  -5.421510 -3.211081 -8.593637 -5.570042     4.0  
5 -7.319962 -10.607784  1.151389 -5.078557 -3.612989     5.0  
6 -6.809922 -12.596327  2.683211 -4.342238 -3.907392     6.0  
7 -1.502881  -6.723585 -2.647116 -2.846984  0.620602     7.0  
8 -2.791287  -9.713887  0.064343 -3.384192 -3.268591     8.0  
9 -5.587467  -8.764580  1.631364 -7.663069 -4.031754     9.0

#### 2. Checker les variables quantitatives/qualitatives et les valeurs manquantes 

In [5]:
mydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Fe1     211 non-null    float64
 1   Fe2     211 non-null    float64
 2   Fe3     211 non-null    float64
 3   Fe4     211 non-null    float64
 4   Fe5     211 non-null    float64
 5   Fe6     211 non-null    float64
 6   Fe7     211 non-null    float64
 7   Fe8     211 non-null    float64
 8   Fe9     211 non-null    float64
 9   Fe10    211 non-null    float64
 10  Fe11    211 non-null    float64
 11  Fe12    211 non-null    float64
 12  Target  211 non-null    float64
dtypes: float64(13)
memory usage: 21.6 KB


#### 3. Visualiser les targets

In [6]:
mydata['Target']

0      0.0
1      1.0
2      2.0
3      3.0
4      4.0
      ... 
206    6.0
207    7.0
208    8.0
209    9.0
210    0.0
Name: Target, Length: 211, dtype: float64

#### 4. Notre variable target (Y) est 'gender', Récuprer X et y à partir du jeu de données 

In [7]:
y = mydata['Target']
X = mydata.iloc[:,:-1]
X.shape

(211, 12)

#### 5. Diviser la DataSet en donneés d'apprentissage et de test (20% pour le test)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#### 6. Appliquer une normalisation centrée-réduite aux données en utilisant "StandardScaler"

In [9]:
scaler = StandardScaler()
print(scaler.fit(mydata))

StandardScaler()


#### 7. Développer votre meilleur modèle de classification

# xgboost

In [10]:
from xgboost import XGBClassifier

In [11]:
from xgboost import XGBClassifier
modelexgb = XGBClassifier()
modelexgb.fit(X_train, y_train)
y_pred=modelexgb.predict(X_test)

C:\Users\utilisateur\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[11:27:08] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [12]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print('Accuracy: %.2f%%\n' % (accuracy * 100.0))
print('Matrice de confusion\n')
print(confusion)

Accuracy: 76.74%

Matrice de confusion

[[6 0 0 0 0 0 0 0 0 0]
 [0 3 0 1 0 0 0 0 0 0]
 [0 1 3 0 0 0 0 0 1 0]
 [0 2 0 3 0 0 0 0 0 0]
 [1 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 1 0 3 0 0]
 [0 0 1 0 0 0 0 0 2 0]
 [0 0 1 0 0 0 0 0 0 4]]


# arbre de decision

In [13]:
modeledtree = DecisionTreeClassifier()
modeledtree.fit(X_train, y_train)
y_pred=modeledtree.predict(X_test)

In [14]:
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print('Accuracy: %.2f%%\n' % (accuracy * 100.0))
print('Matrice de confusion\n')
print(confusion)

Accuracy: 60.47%

Matrice de confusion

[[4 0 0 2 0 0 0 0 0 0]
 [0 3 0 1 0 0 0 0 0 0]
 [1 0 3 0 0 0 0 0 0 1]
 [1 3 0 1 0 0 0 0 0 0]
 [1 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 1 0 2 0 1]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 2 0 0 1 0 2]]


# random forest

In [15]:
modeleforest = RandomForestClassifier()
modeleforest.fit(X_train, y_train)
y_pred=modeleforest.predict(X_test)

In [16]:
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print('Accuracy: %.2f%%\n' % (accuracy * 100.0))
print('Matrice de confusion\n')
print(confusion)

Accuracy: 90.70%

Matrice de confusion

[[6 0 0 0 0 0 0 0 0 0]
 [1 3 0 0 0 0 0 0 0 0]
 [1 0 4 0 0 0 0 0 0 0]
 [0 1 0 4 0 0 0 0 0 0]
 [0 0 0 0 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 0 5]]


# SVM

In [17]:
modelesvm = SVC()
modelesvm.fit(X_train, y_train)
y_pred=modelesvm.predict(X_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print('Accuracy: %.2f%%\n' % (accuracy * 100.0))
print('Matrice de confusion\n')
print(confusion)

Accuracy: 58.14%

Matrice de confusion

[[5 1 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 3 0]
 [0 5 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 4 0 0]
 [0 0 1 0 0 0 0 0 2 0]
 [0 0 0 0 0 5 0 0 0 0]]


# MLP

In [19]:
modelemlp = MLPClassifier()
modelemlp.fit(X_train, y_train)
y_pred=modelemlp.predict(X_test)

C:\Users\utilisateur\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [20]:
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print('Accuracy: %.2f%%\n' % (accuracy * 100.0))
print('Matrice de confusion\n')
print(confusion)

Accuracy: 81.40%

Matrice de confusion

[[6 0 0 0 0 0 0 0 0 0]
 [0 2 0 2 0 0 0 0 0 0]
 [0 1 4 0 0 0 0 0 0 0]
 [0 2 0 3 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 4 0 0]
 [0 0 1 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 5]]


In [21]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV

In [22]:
pipe_rf = Pipeline([('scl', StandardScaler()),
                    ('RF',RandomForestClassifier(random_state=4))])
pipe_svm = Pipeline([('scl', StandardScaler()),
                     ('SVM', SVC(random_state=4))])

In [23]:
param_range = [1, 2, 3, 4, 5, 6]
param_range_fl = [1.0, 0.5, 0.1]
n_estimators = [50,100,150]
learning_rates = [.1,.2,.3]

rf_param_grid = [{'RF__min_samples_leaf': param_range,
                   'RF__max_depth': param_range,
                   'RF__min_samples_split': param_range[1:]}]

svm_param_grid = [{'SVM__kernel': ['linear', 'rbf'], 
                    'SVM__C': param_range}]


In [24]:
rf_grid_search = GridSearchCV(estimator=pipe_rf,
        param_grid=rf_param_grid,
        scoring='accuracy',
        cv=3)

svm_grid_search = GridSearchCV(estimator=pipe_svm,
        param_grid=svm_param_grid,
        scoring='accuracy',
        cv=3)


In [26]:
grids = [rf_grid_search, svm_grid_search]
for pipe in grids:
    pipe.fit(X_train,y_train)

In [27]:
grid_dict = {0: 'Decision Trees',1: 'Support Vector Machines'}

for i, model in enumerate(grids):
    print('{} Test Accuracy: {}'.format(grid_dict[i],
    model.score(X_test,y_test)))
    print('{} Best Params: {}'.format(grid_dict[i],          
model.best_params_))

Decision Trees Test Accuracy: 0.8372093023255814
Decision Trees Best Params: {'RF__max_depth': 6, 'RF__min_samples_leaf': 4, 'RF__min_samples_split': 2}
Support Vector Machines Test Accuracy: 0.8372093023255814
Support Vector Machines Best Params: {'SVM__C': 5, 'SVM__kernel': 'rbf'}


from sklearn.metrics import plot_confusion_matrix
plot_confusion_matrix(xgb_grid_search, X_test, y_test)

# Application en Temps Réel

In [38]:
from Tools.tools import rec

In [43]:
scaler=StandardScaler().fit(X_train,y_train)
X_train = scaler.transform(X_train)
opti=RandomForestClassifier(n_estimators = 50).fit(X_train,y_train)

rec(scaler,opti)

Attention, l'enregistrement commence dans :
5
4
3
2
1
0
Prononcer votre Digit : 
------------------
Digit :  6.0
------------------
